//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Areas_Funcionario_Views_Shared__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Areas_Funcionario_Views_Shared__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                                     __o = Url.Action("Index", "Principal", new { area = "Funcionario" });


#line default
#line hidden

#line 5 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Planos |", "ListarPlano", "Plano", new { area = "Funcionario" }, new { @class = "nav-link" });


#line default
#line hidden

#line 6 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Clinícas |", "ListarBeneficio", "Beneficio", new { area = "Funcionario" }, new { @class = "nav-link" });


#line default
#line hidden

#line 7 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Atendimentos |", "ListarTipo", "Tipo", new { area = "Funcionario" }, new { @class = "nav-link" });


#line default
#line hidden

#line 8 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Funcionários", "ListarRaca", "Raca", new { area = "Funcionario" }, new { @class = "nav-link" });


#line default
#line hidden

#line 9 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 10 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Planos", "ListarPlano", "Plano", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidden

#line 11 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Benefícios", "ListarBeneficio", "Beneficio", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidden

#line 12 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Tipos de Animal", "ListarTipo", "Tipo", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidden

#line 13 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Raça", "ListarRaca", "Raca", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidden

#line 14 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Clinicas", "ListarClinica", "Clinica", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidden

#line 15 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Atendimentos", "ListarAtendimento", "Atendimento", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidden

#line 16 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                       __o = Html.ActionLink("Formas de Pagamento", "ListarFormaPagamento", "FormaPagamento", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidden

#line 17 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 18 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 19 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\3\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                                     __o = Url.Action("Index", "Home");


#line default
#line hidden

#line 5 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Planos |", "ListarPlano", "Plano", new { area = "Funcionario" }, new { @class = "nav-link" });


#line default
#line hidden

#line 6 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Benefícios |", "ListarBeneficio", "Beneficio", new { area = "Funcionario" }, new { @class = "nav-link" });


#line default
#line hidden

#line 7 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Tipos de Animal |", "ListarTipo", "Tipo", new { area = "Funcionario" }, new { @class = "nav-link" });


#line default
#line hidden

#line 8 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Tipos de Animal |", "ListarTipo", "Tipo", new { area = "Funcionario" }, new { @class = "nav-link" });


#line default
#line hidden

#line 9 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Clinicas |", "ListarClinica", "Clinica", new { area = "Funcionario" }, new { @class = "nav-link" });


#line default
#line hidden

#line 10 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Atendimentos |", "ListarAtendimento", "Atendimento", new { area = "Funcionario" }, new { @class = "nav-link" });


#line default
#line hidden

#line 11 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Formas de Pagamento", "ListarFormaPagamento", "FormaPagamento", new { area = "Funcionario" }, new { @class = "nav-link" });


#line default
#line hidden

#line 12 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 13 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                           __o = Html.ActionLink("Planos", "ListarPlano", "Plano", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidden

#line 14 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                           __o = Html.ActionLink("Benefícios", "ListarBeneficio", "Beneficio", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidden

#line 15 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                           __o = Html.ActionLink("Tipos de Animal", "ListarTipo", "Tipo", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidden

#line 16 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                           __o = Html.ATipos de Animalk("CListarTipostarTipo", "Clinica", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidden

#line 17 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layou                           __o = Html.ActionLink("Clinicas", "ListarClinica", "Clinica", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidden

#line 18 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
t.cshtml"
                           __o = Html.ActionLink("Atendimentos", "ListarAtendimento", "Atendimento", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidde19

#line 18 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
                           __o = Html.ActionLink("Formas de Pagamento", "ListarFormaPagamento", "FormaPagamento", new { area = "Funcionario" }, new { @class = "" });


#line default
#line hidde20

#line 19 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidde21

#line 20 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidde22

#line 21 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Areas\Funcionario\Views\Shared\_Layout.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
