//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PoliticasPrivacidade_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_PoliticasPrivacidade_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\marcu\AppData\Local\Temp\25F70570E4354ADDF928A4364FE69C4AEDE8\2\Tcc\Views\Home\PoliticasPrivacidade.cshtml"
  
    ViewBag.Title = "Políticas de Privacidade";


#line default
#line hidden
}
}
}
